version: '3.8'

services:
  webapp:
    build: .
    container_name: webapp
    ports:
      - "5000:5000"
    networks:
      - elastic
    volumes:
      - ./es/data:/usr/share/es/data
    external_links:
      - elasticsearch

networks:
  elastic:
    external: true